repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-vcs-permalinks
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.4.0
  hooks:
  - id: eslint
    additional_dependencies: ['eslint@8.3.0','eslint-plugin-react','@typescript-eslint/eslint-plugin', 'typescript','typescript-eslint', '@typescript-eslint/parser']
    files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
    types: [file]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
    - id: detect-secrets
      args: ["--baseline", ".secrets.baseline"]
      exclude: .*/tests/.*
