name: e2e
on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
            name: cypress-snapshots
            path: /home/runner/work/digital_marketplace/digital_marketplace/cypress/screenshots/
